sick_scan2: # configuration for sick_scan2_tim_7xxS: For compatibility with ros versions previous to foxy, node and parameter name changed to sick_scan2 for all supported scanner. The type of scanner is configured by scanner_name only.
  ros__parameters:
    hostname : "192.168.0.1"
    frame_id : "cloud"
    scanner_name : "sick_tim_7xxS"
    port : 2112
    min_ang : -2.35619449 #in lidar cordinate frame  see ../doc/3d_coordinate_system_comp.png
    max_ang : 2.35619449 #in lidar cordinate frame  see ../doc/3d_coordinate_system_comp.png
    max_range : 25.0 #in meters
